package com.jlp.pmu.enums;

public enum PrinterJobStatus {
	DATA_TRANSFER_COMPLETE,
	JOB_CANCELED,
	JOB_COMPLETE,
	JOB_FAILED,
	NO_MORE_EVENTS,
	REQUIRES_ATTENTION,
	PRINTER_SERVICE_UNAVAILABLE,
	JOB_NOT_COMPLETE,
	PRINTER_QUEUE_FULL;
}
